function [srp_force_B__N, srp_torque_B__Nm] ...
            = execute(position_BI_I__m,...
                        sun_position_SI_I__m, ...
                        attitude_quaternion_BI, ...
                        pressure__N_per_m2, ...
                        bodies_rotation_angles__rad, ...
                        ParametersPanelMethodSRP)
% execute - Calculate the aerodynamic force and torque in the body frame
%
% [aerodynamic_force_B__N, aerodynamic_torque_B__Nm] ...
%             = execute(position_BI_I__m, ...  
%                         sun_position_SI_I__m, ...
%                         attitude_quaternion_BI, ...
%                         pressure__N_per_m2, ...
%                         bodies_rotation_angles__rad, ...
%                         ParametersSimplifiedVleoAerodynamics)
%
%   Inputs:
%   position_BI_I__m: 3x1 inertial position of the body
%   sun_position_SI_I__m: 3x1 inertial position of the sun
%   attitude_quaternion_BI: 4x1 quaternion of body frame attitude
%   pressure__N_per_m2: Incoming scalar solar radiation pressure N/m^2
%   bodies_rotation_angles__rad: 1xN matrix of rotation angles of bodies in body frame
%   ParametersSimplifiedVleoAerodynamics: Parameters of the SimplifiedVleoAerodynamics model
%
%   Outputs:
%   aerodynamic_force_B__N: 3x1 vector of aerodynamic force in body frame
%   aerodynamic_torque_B__Nm: 3x1 vector of aerodynamic torque in body frame
%

%% Abbreviations
dir_I_I = position_BI_I__m-sun_position_SI_I__m;
incoming_direction_I_I = dir_I_I/norm(dir_I_I);

%% Call panel based pressure respon from external namespace
% Prepare inputs to model
Param = ParametersPanelMethodSRP;
bodies = Param.bodies;

% Call model
[srp_force_B__N, srp_torque_B__Nm] ...
    = panel_based_pressure_response.panelMethod(attitude_quaternion_BI, ...
                                                incoming_direction_I_I, ...
                                                pressure__N_per_m2, ...
                                                bodies, ...                                                       
                                                bodies_rotation_angles__rad);

end