function [total_force_B__N, total_torque_B__Nm] ...
            = execute(attitude_quaternion_BI, ...
                        velocity_I_I__m_per_s, ...
                        wind_velocity_I_I__m_per_s, ...
                        surface_temperatures__K, ...
                        ParametersNewVleoAerodynamics,...
                        atmosphere_mass_density__kg_per_m3, ...
                        atmosphere_number_density__1_per_m3, ...
                        atmosphere_temperature__K,...
                        surface_energy_accommodation_coefficients)
% execute - Calculate the aerodynamic force and torque in the body frame
%
%   [aerodynamic_force_B__N, aerodynamic_torque_B__Nm] ...
%       = execute(attitude_quaternion_BI, ...
%                 angular_velocity_BI_B__rad_per_s, ...
%                 velocity_I_I__m_per_s, ...
%                 wind_velocity_I_I__m_per_s, ...
%                 atmosphere_mass_density__kg_per_m3, ...
%                 atmosphere_number_density__1_per_m3, ...
%                 atmosphere_temperature__K, ...
%                 bodies_rotation_angles__rad, ...
%                 ParametersSimplifiedVleoAerodynamics)
%
%   Inputs:
%   attitude_quaternion_BI: 4x1 quaternion of body frame attitude
%   angular_velocity_BI_B__rad_per_s: 3x1 vector of body frame angular velocity
%   velocity_I_I__m_per_s: 3x1 vector of velocity in inertial frame
%   wind_velocity_I_I__m_per_s: 3x1 vector of wind velocity in inertial frame
%   atmosphere_mass_density__kg_per_m3: Mass density of atmosphere in kg/m^3
%   atmosphere_number_density__1_per_m3: Number density of atmosphere in 1/m^3
%   atmosphere_temperature__K: Temperature of atmosphere in K
%   bodies_rotation_angles__rad: 1xN matrix of rotation angles of bodies in body frame
%   ParametersSimplifiedVleoAerodynamics: Parameters of the SimplifiedVleoAerodynamics model
%
%   Outputs:
%   aerodynamic_force_B__N: 3x1 vector of aerodynamic force in body frame
%   aerodynamic_torque_B__Nm: 3x1 vector of aerodynamic torque in body frame
%

%% Abbreviations
Param = ParametersNewVleoAerodynamics;
rho = atmosphere_mass_density__kg_per_m3;
n = atmosphere_number_density__1_per_m3;
atmos_temp__K = atmosphere_temperature__K;
alpha_e = surface_energy_accommodation_coefficients;


%% Create Aeroconditions object
% Calculate mean particle mass in kg
mean_particle_mass__kg = rho / n;

% aero conditions in parameter anlegen und dann mit jedem call der shading pipeline die 
% neuen variablen überschreiben 
% Param.aero_conditions.rho = x
% ...
aero_conditions = new_vleo_aerodynamics_core.AeroConditions(...
                rho,...
                atmos_temp__K,...
                mean_particle_mass__kg,...
                alpha_e);

% Delete handle to AeroConditions object when function exits
% cleanup_aero_conditions = onCleanup(@() delete(aero_conditions)); 


%% Prepare surface temperature
surf_temp__K = surface_temperatures__K;      % Param.bodies.surface_temperature__K;


%% Calculate relative velocity in body frame

% Calculate relative velocity in inertial frame
relative_velocity_I__m_per_s = velocity_I_I__m_per_s - wind_velocity_I_I__m_per_s;

% Transform relative velocity from inertial frame I to body frame B
relative_velocity_B__m_per_s = ...
    smu.unitQuat.att.transformVector( ...
        attitude_quaternion_BI, ...
        relative_velocity_I__m_per_s);


% Panel visibility check (optional)
panel_visibility = ...
    Param.shading_pipeline.shade( ...
        relative_velocity_B__m_per_s);
%
%fprintf("Number of triangles: %d\n", ...
%    Param.satellite.get_num_triangles());
%
%fprintf("Visibility vector length: %d\n", ...
%    numel(panel_visibility));
%
%fprintf("Minimum visibility: %.6e\n", ...
%    min(panel_visibility));
%
%fprintf("Maximum visibility: %.6e\n", ...
%    max(panel_visibility));
%
%fprintf("Mean visibility: %.6e\n", ...
%    mean(panel_visibility));
%
%fprintf("Visible triangles: %d\n", ...
%    nnz(panel_visibility > 0));

%% visualize shading result
new_vleo_aerodynamics_core.show_mesh(Param.satellite, panel_visibility, relative_velocity_B__m_per_s);


%% Call HybridAeroLoadCalculator to compute total aerodynamic load
 [total_force_B__N, total_torque_B__Nm] = Param.load_calculator.calc_aero_load(...
                                        relative_velocity_B__m_per_s, ... 
                                        surf_temp__K, ...
                                        aero_conditions);


end