function [force_B__N, torque_B__Nm] ...
             = MatlabRuntime(relative_velocity_B__m_per_s, ...
                        mass_density__kg_per_m3, ...
                        number_density__1_per_m3, ...
                        atmosphere_temperature__K, ...
                        ParametersNewVleoAerodynamics)

% Runs the non-code-generatable MEX wrapper classes in the MATLAB runtime.

%% Persistent aerodynamic objects
    % persistent sentman
    % persistent satellite
    % persistent shading_pipeline
    % persistent load_calculator


%% Abreviations
Param = ParametersNewVleoAerodynamics;


%% Hard coded path to the mesh file
mesh_file_path = "C:\Users\st173938\Desktop\sadycos\UserFiles\Configurations\+ExampleMission\@NewAerodynamics\obj_files\body.obj";


%% Load parameters from the ParametersNewVleoAerodynamics structure
surface_temperature__K = Param.surface_temperature__K;
alpha_e = Param.surface_energy_accommodation_coefficient;
temperature_ratio_method = Param.temperature_ratio_method;
shading_algorithm = Param.shading_algorithm;
shading_resolution = Param.shading_resolution;


%% Initialize persistent aerodynamic objects if they are empty
% Check if any of the persistent objects are empty
%needs_initialization = ...
%    isempty(sentman) || ...
%    isempty(satellite) || ...
%    isempty(shading_pipeline) || ...
%    isempty(load_calculator);
%
%
%if needs_initialization
sentman = ...
    new_vleo_aerodynamics_core.Sentman(temperature_ratio_method);

satellite = ...
    new_vleo_aerodynamics_core.RotatableMeshSatellite( ...
        mesh_file_path);

shading_pipeline = ...
    new_vleo_aerodynamics_core.ShadingPipeline( ...
        satellite, ...
        shading_algorithm, ...
        shading_resolution);

load_calculator = ...
    new_vleo_aerodynamics_core.HybridAeroLoadCalculator( ...
        satellite, ...
        shading_pipeline, ...
        sentman);
%end

%% Calculate the mean particle mass in kg
particle_mass__kg = ...
    mass_density__kg_per_m3 / number_density__1_per_m3;


%% Create an AeroConditions object to hold the current atmospheric conditions
aero_conditions = ...
    new_vleo_aerodynamics_core.AeroConditions( ...
        mass_density__kg_per_m3, ...
        atmosphere_temperature__K, ...
        particle_mass__kg, ...
        alpha_e);


%% Compute the aerodynamic force and torque using the HybridAeroLoadCalculator
[force_B__N, torque_B__Nm] = load_calculator.calc_aero_load( ...
        relative_velocity_B__m_per_s, ...
        surface_temperature__K, ...
        aero_conditions);


end

