classdef NewVleoAerodynamics < ModelBase

    methods (Static)
                        
        [total_force_B__N, total_torque_B__Nm] ...
            = execute(attitude_quaternion_BI, ...
                        velocity_I_I__m_per_s, ...
                        wind_velocity_I_I__m_per_s, ...
                        atmosphere_mass_density__kg_per_m3, ...
                        atmosphere_number_density__1_per_m3, ...
                        atmosphere_temperature__K, ...
                        ParametersNewVleoAerodynamics)

        
        %[force_B__N, torque_B__Nm] ...
        %     = MatlabRuntime(relative_velocity_B__m_per_s, ...
        %                mass_density__kg_per_m3, ...
        %                number_density__1_per_m3, ...
        %                atmosphere_temperature__K, ...
        %                ParametersNewVleoAerodynamics)


        test
                        

    end

    methods (Access = public)

        function obj = NewVleoAerodynamics(surface_temperature__K, ...
                                                    surface_energy_accommodation_coefficient, ...
                                                    temperature_ratio_method, ...
                                                    shading_algorithm, ...
                                                    shading_resolution)


            % build Parameters struct expected by execute/MatlabRuntime
            Parameters.surface_temperature__K = surface_temperature__K;
            Parameters.surface_energy_accommodation_coefficient = surface_energy_accommodation_coefficient;
            Parameters.temperature_ratio_method = temperature_ratio_method;
            Parameters.shading_algorithm = shading_algorithm;
            Parameters.shading_resolution = shading_resolution;


            %% Set Parameters in ModelBase Constructor
            obj = obj@ModelBase("Parameters", Parameters);

        end
    end
end