classdef AttitudeError < ModelBase
    methods (Static)

        [error_quaternion_RB, ...
            angular_velocity_error_RB_B__rad_per_s, ...
            angular_acceleration_error_RB_B__rad_per_s2] ...
            = execute(reference_frame_attitude_quaternion_RI, ...
                        body_frame_attitude_quaternion_BI, ...
                        reference_angular_velocity_RI_R__rad_per_s, ...
                        body_angular_velocity_BI_B__rad_per_s, ...
                        reference_angular_acceleration_RI_R__rad_per_s2, ...
                        body_angular_acceleration_BI_B__rad_per_s2)

    end
end