classdef NewAerodynamics < ExampleMission.DefaultConfiguration
    
        methods (Static)

                parameters_cells = configureParameters()
                
                [PlantFeedthrough, ...
                 LogPlantDynamics, ...    
                 PlantStatesDerivatives] ...
                 = plantDynamics(PlantFeedthrough, ...
                                     LogPlantDynamics, ...
                                     PlantStatesDerivatives, ...
                                     EnvironmentConditions, ...
                                     ActuatorsOutputs, ...
                                     PlantStates, ...
                                     ParametersPlant)

        end
                
end



