%% Script to test the panel method solar radiation pressure model
clc
clear
close all

%% Input
time_current_mjd = 6.1000e+04;
position_BI_I__m = [6.771e6;0;0];
attitude_quaternion_BI = [1;0;0;0];
bodies_rotation_angles__rad = zeros(5,1);

%% Initialize Panel Method SRP
% Get absolute path of this file's folder
[this_folder,~,~] = fileparts(mfilename("fullpath"));
% Get absolute paths of all obj files
obj_files = string(fullfile(this_folder, 'obj_files', 'body.obj'));
rotation_hinge_points_CAD = zeros(3,1);

rotation_directions_CAD = [1; 0; 0];

reflectivities = num2cell(0.21);

DCM_B_from_CAD = [0, -1, 0;...
                    -1, 0, 0; ...
                    0, 0, -1];

center_of_mass_CAD = [0; 2; 0];

ParametersPanelMethodSRP = PanelMethodSRP(obj_files, ...
                                            rotation_hinge_points_CAD, ...
                                            rotation_directions_CAD, ...
                                            reflectivities, ...
                                            DCM_B_from_CAD, ...
                                            center_of_mass_CAD, ...
                                            false);
%% Sun and Moon Positions
[sun_position_SI_I__m,moon_position_MI_I__m] = SimpleSolarLunarPosRelEarth.execute(time_current_mjd);

% override for testing purposes
sun_position_SI_I__m = [1;0;0]*norm(sun_position_SI_I__m);
moon_position_MI_I__m = [1;0;0]*norm(moon_position_MI_I__m);

%% Model for solar irradiance
nrltiseParams = NRLTSI21(mjuliandate(datetime('now')),42536000);

irradiance_at_sat_I_I__W_per_m2 ...
        = NRLTSI21.execute(position_BI_I__m, ...
                            sun_position_SI_I__m, ...
                            time_current_mjd, ...
                            nrltiseParams.Parameters.Nrltsi21Data);

%% Model for Sun occultation by Earth and the Moon
earth_radius__m = 6378e3; % mean radius
sun_radius__m = 696340e3; % mean radius
moon_radius__m = 1737.4e3; % mean radius
ParametersEarthMoonOccultation = EarthMoonOccultation(earth_radius__m, ...    
                                                        sun_radius__m, ...
                                                        moon_radius__m);
[sun_visibility_fraction] ...
       = EarthMoonOccultation.execute(position_BI_I__m, ...
                                       sun_position_SI_I__m, ...
                                       moon_position_MI_I__m, ...
                                       ParametersEarthMoonOccultation.Parameters);

irradiance_at_sat_I_I__W_per_m2 = sun_visibility_fraction*irradiance_at_sat_I_I__W_per_m2

%% Execute the model
[srp_force_B__N, srp_torque_B__Nm] ...
    = PanelMethodSRP.execute(attitude_quaternion_BI, ...
                               irradiance_at_sat_I_I__W_per_m2, ...
                               bodies_rotation_angles__rad, ...
                               ParametersPanelMethodSRP.Parameters)