function build_hwm14_mex

% This function builds the HWM14 Fortran MEX file into the wrapper folder.

gateway_path = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_gateway.F90");

hwm14lib_path = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build",...
    "libhwm14.a");

out_path = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_mex");

mex('-v', '-R2018a', ... 
'-output', out_path, ...
gateway_path, ...
hwm14lib_path);

end