function build_hwm_ifc_mex

% This function builds the HWM_interface Fortran MEX file into the wrapper folder.

mod_dir = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "include"));

gateway_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_ifc_gateway.F90"));

libhwmifc_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "libhwm_ifc.a"));

libhwm14_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "libhwm14.a"));

out_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14ifc_mex"));


mex('-v', '-R2018a', ... 
['-I' mod_dir], ...
gateway_path, ...
libhwmifc_path, ...
libhwm14_path, ...
'-output', out_path);

end