classdef RigidBodyMechanics < ModelBase
    methods (Static)
        
        [position_derivative_BI_I__m_per_s, ...
            velocity_derivative_BI_I__m_per_s2, ...
            attitude_quaternion_derivative__1_per_s, ...
            angular_velocity_derivative_BI_B__rad_per_s2] ...
            = execute(mass__kg, ...
                        inertia_B_B__kg_m2, ...
                        net_force_I__N, ...
                        net_torque_B__N_m, ...
                        velocity_BI_I__m_per_s, ...
                        attitude_quaternion_BI, ...
                        angular_velocity_BI_B__rad_per_s)
                        
    end
end