%% Script to test the panel method solar radiation pressure model
clc
clear
close all


% Aerodynamics
% Get absolute path of this file's folder
[this_folder,~,~] = fileparts("C:\Users\pjhge\Documents\IFR_HiWi\sadycos_dev\UserFiles\Configurations\+ExampleMission\@DefaultConfiguration\obj_files");
% Get absolute paths of all obj files
obj_files = string(fullfile(this_folder, 'obj_files', 'body.obj'));
rotation_hinge_points_CAD = zeros(3,1);

rotation_directions_CAD = [1; 0; 0];

reflectivities = num2cell(0.21);

DCM_B_from_CAD = [0, -1, 0;...
                    -1, 0, 0; ...
                    0, 0, -1];

center_of_mass_CAD = [0; 2; 0];

parameters = PanelMethodSRP(obj_files, ...
                            rotation_hinge_points_CAD, ...
                            rotation_directions_CAD, ...
                            reflectivities, ...
                            DCM_B_from_CAD, ...
                            center_of_mass_CAD, ...
                            true);
%% Execute the model
attitude_quaternion_BI = [1;0;0;0];
incoming_direction_I_I__m_per_s = [1;0;0];
pressure__N_per_m2 = 4.56e-6; %N/m^2
bodies_rotation_angles__rad = zeros(5,1);

[srp_force_B__N, srp_torque_B__Nm] ...
    = PanelMethodSRP.execute(attitude_quaternion_BI, ...
                            incoming_direction_I_I__m_per_s, ...
                            pressure__N_per_m2, ...
                            bodies_rotation_angles__rad, ...
                            parameters.Parameters);