%% Script to test the panel method solar radiation pressure model
clc
clear
close all

% Get absolute path of this file's folder
[this_folder,~,~] = fileparts("C:\Users\pjhge\Documents\IFR_HiWi\sadycos_dev\UserFiles\Configurations\+ExampleMission\@DefaultConfiguration\obj_files");
% Get absolute paths of all obj files
obj_files = string(fullfile(this_folder, 'obj_files', 'body.obj'));
rotation_hinge_points_CAD = zeros(3,1);

rotation_directions_CAD = [1; 0; 0];

reflectivities = num2cell(0.21);

DCM_B_from_CAD = [0, -1, 0;...
                    -1, 0, 0; ...
                    0, 0, -1];

center_of_mass_CAD = [0; 2; 0];

srpParams = PanelMethodSRP(obj_files, ...
                            rotation_hinge_points_CAD, ...
                            rotation_directions_CAD, ...
                            reflectivities, ...
                            DCM_B_from_CAD, ...
                            center_of_mass_CAD, ...
                            true);
%% Model for solar irradiance
nrltiseParams = NRLTSI21(mjuliandate(datetime('now')),42536000);

total_solar_irradiance_at_1AU_W_per_m2 ...
    = NRLTSI21.execute(6.1000e+04,nrltiseParams.Parameters.Nrltsi21Data);

%% Execute the model
position_BI_I__m = [6.771e6;0;0];
attitude_quaternion_BI = [1;0;0;0];
bodies_rotation_angles__rad = zeros(5,1);

time_current_mjd = juliandate(datetime("now"));

[srp_force_B__N, srp_torque_B__Nm] ...
    = PanelMethodSRP.execute(position_BI_I__m,...
                             attitude_quaternion_BI, ...
                             time_current_mjd, ...
                             total_solar_irradiance_at_1AU_W_per_m2, ...
                             bodies_rotation_angles__rad, ...
                             srpParams.Parameters)