function createHWMmexFunction()
% Function to create the MEX function for the AtmosphericVelocity class
% by first buildung the hwm14_gemini3d library and then creating the MEX function

%% Build the hwm14_gemini3d library

% Get the full path of the current file
[this_folder,~,~] = fileparts(mfilename('fullpath'));
% Go one folder up (to hwm14)
[parent_folder,~,~] = fileparts(this_folder);
% Build the path to the hwm14_gemini3d directory
hwm_dir = fullfile(parent_folder, 'hwm14_gemini3d');

% Check if the build folder exists, if so, delete it
%{
 build_folder = fullfile(hwm_dir, 'build');

if exist(build_folder,'dir')
    rmdir(build_folder,'s')
end 
%}

% switch to the hwm14_gemini3d directory
cd(hwm_dir);

% In the following the 
% locate the installation directory of MATLAB and safe it in a variable
matlab_root = matlabroot;
% build the path to the mingw_w64.instrset directory
mingw_dir = fullfile(matlab_root,...
    'SupportPackages','R2024b','3P.instrset','mingw_w64.instrset');
% Set the environment variable MW_MINGW64_LOC to the path of the mingw_w64.instrset directory
setenv('MW_MINGW64_LOC', mingw_dir);

% Add mingw bin directory temporarily to PATH environment variable
setenv('PATH',[fullfile(mingw_dir,'bin') pathsep getenv('PATH')]);

% build the library using cmake and mingw
% set the Fortran compiler to gfortran to ensure that the same compiler 
% is used for both the library and the MEX function
% add the flag -fdefault-integer-8 to use 64 bit integers by default
cmd = ['cmake -S . -B build -G "MinGW Makefiles" ' ...
       '-DCMAKE_Fortran_COMPILER=gfortran ' ...
       '-DCMAKE_Fortran_FLAGS="-fdefault-integer-8"'];
status = system(cmd);

if status ~= 0
    error('CMake configuration failed')
end

fprintf('CMake configuration successful.\n')


%% Create the MEX function

mod_dir = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "include"));

gateway_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_ifc_gateway.F90"));

libhwmifc_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "libhwm_ifc.a"));

libhwm14_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "libhwm14.a"));

out_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14ifc_mex"));


mex('-v', '-R2018a', ... 
['-I' mod_dir], ...
gateway_path, ...
libhwmifc_path, ...
libhwm14_path, ...
'-output', out_path);

end



