function build_hwm14_mex

% This function builds the HWM14 Fortran MEX file into the wrapper folder.

gateway_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_gateway.F90"));

lib_dir = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build"));

out_path = char(fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_mex"));

mex('-R2018a', ... 
'-output', out_path, ...
gateway_path, ...
['-L', lib_dir], '-lhwm14', ...
    '-lgfortran', '-lquadmath');

end