function build_hwm_ifc_mex

% This function builds the HWM_interface Fortran MEX file into the wrapper folder.

gateway_path = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14_gateway.F90");

lib_dir = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build");
    
mod_dir = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "hwm14_gemini3d", ...
    "build", ...
    "include");

out_path = fullfile( ...
    "Core", ...
    "ModelsLibrary", ...
    "Environment", ...
    "EarthAtmosphere", ...
    "hwm14", ...
    "wrapper", ...
    "hwm14ifc_mex");

mex('-v', '-R2018a', ... 
['-I' mod_dir], ...
['-L' lib_dir], ...
gateway_path, ...
'-lhwm_ifc',... 
'-lhwm14', ...
'-output', out_path);

end