function forceRecompile(obj)
%% forceRecompile - brute-force method to force Simulink to recompile the 
% referenced code within Matlab Function Blocks to reflect changes made within
% simulations without restarting Matlab

load_system("sadycos");
blockPaths = ["sadycos/Environment/Environment",...
              "sadycos/GNC Algorithms/GNC Algorithms",...
              "sadycos/Satellite/Plant/Plant Dynamics",...
              "sadycos/Satellite/Plant/Plant Output",...
              "sadycos/Satellite/Sensors/Sensors"];

% Loop over relevant matlab function blocks
for i=1:numel(blockPaths)
    tag_matlab_function_block(blockPaths(1,i));
end

end

function tag_matlab_function_block(blockPath)
    % Generate unique timestamp comment
    timestamp = datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss');
    headerComment = ['% Autogenerated: last recompiled ' char(timestamp)];

    % Read existing function script
    config = get_param(blockPath,"MATLABFunctionConfiguration");
    existingScript = config.FunctionScript;
    scriptLines = strsplit(existingScript, newline);

    % Remove previous recompilation comment if it exists
    if startsWith(scriptLines{1}, '% Autogenerated: last recompiled')
        scriptLines(1) = [];  % Remove old comment
    end

    % Prepend new comment
    updatedScript = strjoin([{headerComment}, scriptLines], newline);

    % Update the block
    config.FunctionScript = updatedScript;

    fprintf('Updated block "%s" with timestamp: %s\n', blockPath, timestamp);
end